//const { application } = require('express');
const express=require('express');
const router=express.Router();
const userController=require('../controllers/users_controller');
router.get('/', userController.profile);
router.use('/posts', require('./posts'));
router.get('/profile', userController.userProfile);
router.get('/sign-up', userController.signup);
router.get('/sign-in', userController.signin);
router.post('/create', userController.create); 
router.post('/create-session', userController.createSession);
module.exports=router;
